site:
  title: Top News
  subtitle: Latest Breaking News
  limit: 25
  theme: theme
  lan: en
  url: https://alltop.news
  link: {year}/{month}/{day}/{title}.html

authors:

build:
  output: public
  port: 8009
